config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

app_name = 'first'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('shop.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

shop/urls.py
from django.urls import path
from .views import *

app_name = 'shop'

urlpatterns = [
    path('', product_in_category, name='product_all'),
    path('<category_id>/', product_in_category, name='product_in_category'),
    path('product/search/',product_search, name="product_search_detail"),
    path('product/<product_id>/', product_detail, name='product_detail'),
    path('product/<product_id>/payment/',product_pay, name='product_pay'),
]

shop/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    description = models.TextField(blank=True)

    class Meta:
        ordering = ['-name']
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('shop:product_in_category', args=[self.id])




class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created', '-updated']

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id])

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import *

# Create your views here.

def product_in_category(request, category_id=None):
    current_category = None
    categories = Category.objects.all()
    products = Product.objects.all()
    if category_id:
        current_category = get_object_or_404(Category, id=category_id)
        products = products.filter(category=current_category)
    return render(request, 'shop/list.html', {'current_category':current_category,
                                              'categories':categories,
                                              'products':products})

def product_detail(request, product_id=None):
    product = get_object_or_404(Product, id=product_id)
    return render(request, 'shop/detail.html', {'product':product})
def product_search(request):
    if request.POST:
        val = request.POST['srch']
        current_product = Product.objects.get(name__startswith=val)
    return render(request, 'shop/detail.html', {'product':current_product})
def product_pay(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    return render(request, 'shop/payment.html', {'product':product})

shop/templates/shop/detail.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}

<div class="row">
    <div class="col-4">
        <img src="{{product.image.url}}" width="100%">
    </div>
    <div class="col">
        <h1 class="display-6">{{product.name}}</h1>
        <p><span class="badge badge-secondary">Price</span>{{product.price}}</p>
        <form action="{% url 'shop:product_pay' product.id %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-primary btn-sm" value="결제">
        </form>
        <h5><span class="badge badge-secondary">Description</span>{{product.description|linebreaks}}</h5>
    </div>
</div>

{% endblock content%}
</body>
</html>

shop/templates/shop/list.html
{% extends 'base.html' %}
{% block title %}Category Page{% endblock %}

{% block content %}
<div class="row">
    <div class="col-2">
        <div class="list-group">
            <a href="/" class="list-group-item">All</a>
            {% for c in categories %}
            <a href="{{c.get_absolute_url}}" class="list-group-item">{{c.name}}</a>
            {% endfor %}
        </div>
    </div>
    <div class="col">
        <div class="alert alert-info">
            {% if current_category %}{{current_category.name}}{% else %}All Products{% endif %}
        </div>
        <div class="row">
            {% for product in products %}
            <div class="col-4">
                <div class="card">
                    <img src="{{product.image.url}}" alt="Product Image">
                    <div class="card-body">
                        <h5 class="card-title">{{product.name}}</h5>
                        <p class="card-text">{{product.description}} <span>{{product.price}}</span></p>
                        <a href="{{product.get_absolute_url}}" class="btn btn-primary">View Detail</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

shop/templates/shop/payment.html
{% extends 'base.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<div class="col-12">
<div class="text-center">
    <div>
        <span class="col-md-10">상품명 : {{product.name}}</span>
    </div>
    <div>
        <span class="col-md-10">가격: <strong>{{product.price}}원</strong></span>
    </div>
    <div>
        <span class="col-md-10">결제가 완료되었습니다.</div>
    </div>
</div>
</div>
{% endblock %}
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <form action="{% url 'shop:product_search_detail' %}" method="post" class="d-flex" style="float:right;">
            {% csrf_token %}
            <input class="form-control me-2" type="text" name="srch" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        <ul class="nav">
            <li class="nav-item"><a href="/" class="active nav-link">Home</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a href="#" class="nav-link">Welcome, {{user.get_username}}</a></li>
                <li class="nav-item"><a href="/accounts/logout/" class="nav-link">Logout</a></li>
                {% else %}
                <li class="nav-item"><a href="/accounts/login/" class="nav-link">Login</a></li>
                {% endif %}
        </ul>
      </div>
</nav>
{% block content %}{% endblock %}
</body>
</html>